#!/usr/bin/python

import math
pi = math.pi
sin = math.sin

sample_rate = 48000
length      = 5
frequency   = 440.0

omega = 2*pi*frequency

angle_step = omega/sample_rate
angle_max = omega*length

n_samples = sample_rate*length
sample=0
while sample < n_samples:
    angle = sample*omega/sample_rate
    time = 1.0*sample/sample_rate
    voltage = sin(angle)
    print time, ":", voltage, ":", int(voltage*32767)
    sample+=1

